### PR TITLE
Code Coverage github action

### PR DESCRIPTION
**Pull request by jagerber48**
Adjust CI github action to upload code coverage to codecov.io.

### CODE REVIEW

**Comment by jagerber48** [comment]
Looks like I got this action working. See https://app.codecov.io/github/lmfit/uncertainties/tree/jagerber48%2Funcertainties%3Afeature%2Fcodecov_github_action.

I made the choice to only upload from the `ubuntu-latest` os test and python version `3.11`. This was because I once heard the suggestion to upload latest minus one so you have some time to fix coverage in case in changes when a new latest python is released.

No strong opinions on which version to publish coverage for.

An alternative possibility is to use flags to denote results from different runs, but I haven't totally gotten flags to work, and this strategy feels like overkill. Just mentioning it for completeness.

This PR will close #195

**Comment by reneeotten** [comment]
I think you should be uploading the coverage for all tests and Codecov will combine them.

**Comment by jagerber48** [comment]
> I think you should be uploading the coverage for all tests and Codecov will combine them.

Ok I’ll switch to that. 

I was worried about how results are interpreted if the coverage is different on different versions. But it’s no problem not to worry about that. I once saw a bug along those lines but it was due to a bug involving coverage and python <= 3.9 I think. Unless the source code branches based on OS or Python version I can’t imagine why there would be meaningful coverage differences between different tests.

**Review by newville — APPROVED** [review]
Thanks - that looks good to me

**Comment by newville** [comment]
@jagerber48 OK, let's try merging this one next...

**Pull request merged**
