### PR TITLE
Use setuptools-scm to ensure all repo files are in sdist

### PR DESCRIPTION
**Pull request by wshanks**
Listing `setuptools_scm` in `pyproject.toml` enables it to be used to determine which files are included in the sdist instead of the older `MANIFEST.in` procedure. `setuptools_scm` just includes every file tracked by `git` which seems fine for this small project.

Additionally, delete `INSTALL.txt` which had outdated installation information.

### CODE REVIEW

**Comment by wshanks** [comment]
Closes #234

**Comment by mgorny** [comment]
Thanks. I can confirm that with this change, `python -m build -s` includes all files in sdist.

**Comment by newville** [comment]
@wshanks Thanks -- we could also use this to set the version number from the git tag, as will

- `pyproject.toml`:
add
```
[tool.setuptools_scm]
write_to = "uncertainties/version.py"
version_scheme = "post-release"
```
and remove

```
version = "3.2.0"
```


- `uncertainties/__init__.py`:

replace 
```
# Numerical version:
__version_info__ = (3, 2, 0)
__version__ = '.'.join(map(str, __version_info__))

```

with

```
from .version import version as __version__
```

It would be OK with me to postpone this until later.

**Review by newville — APPROVED** [review]

**Comment by wshanks** [comment]
I like the idea of using `setuptools-scm` to manage the version. I will look into doing that in a later PR.

**Pull request merged**
