### PR TITLE
Removed two unused imports in two tests.

### PR DESCRIPTION
**Pull request by willynilly**
I removed the unused imports mentioned in the following issue:

https://github.com/lmfit/uncertainties/issues/208

### CODE REVIEW

**Comment by andrewgsavage** [comment]
this is a lot more than just moving two tests as you've changed line spacing and whitespace throughout those files. I assume you've run this through a linter. We'd like to get a linter running in the CI to give formatting throughout. I think changes to formatting should be done after a linter is set up in CI.

**Comment by newville** [comment]
I agree with @andrewgsavage.  Removing the imports is fine, but that should change 2 lines of code.

**Comment by willynilly** [comment]
i am curious. what is the problem with changing line spaces before you add a linter to the build process? my changes passed all the tests.

**Comment by jagerber48** [comment]
> i am curious. what is the problem with changing line spaces before you add a linter to the build process? my changes passed all the tests.

While your efforts to clean up the code base are much appreciated, we should keep each PR as focused as possible so it's more easier for everyone to follow what changes were made where and when. This PR should handle the imports like its title suggests, but the job of whitespace cleanup should be handled in a dedicated PR. As has been said, there's some likelihood we'll have automated CI in the future which will include formatting. It will be best to bundle all the "formatting" changes into a single PR around that time. 

I understand the temptation to "clean up" things like this as you go. But,, I've come to learn, it causes the repo documentation to get muddled some, and this matters more for a heavily used public repo that a team of people work on. So I think it's best practice to avoid "sneaking" general cleanup into PRs dedicated for something else.

**Pull request closed without merging**
