### PR TITLE
Fix readthedocs build

### LINKED ISSUE #254: readthedocs docs not building
The automated build of the docs at readthedocs.org is failing, for example https://readthedocs.org/api/v2/build/24927988.txt
The readthedocs version of the docs is stuck on version 3.2.1.

That build log suggests that it is fetching uncertainties from GitHub and installing stuff in `doc/requirements.txt`, but maybe not actually installing it with `pip install`, and then complaining that the file `uncertainties/version.py` does not exist.   Well, that file is not in the repository and is generated at `pip install` time.  Hm...

### PR DESCRIPTION
**Pull request by jagerber48**
- [x] Closes #254 (insert issue number)
- [x] Executed `pre-commit run --all-files` with no errors
- [x] The change is fully covered by automated unit tests
- [x] Documented in docs/ as appropriate
- [x] Added an entry to the CHANGES file

Readthedocs are still not building. I would like to test this PR on RTD before merging it in since it's taking a few tries to get this working. It's possible to do this test on a side branch like this while keeping the docs version hidden from the public.

@lebigot could you please make me and the other uncertainties maintainers to be maintainers on the uncertainties readthedocs project?

I believe this can be done with something along the lines of
- Go to readthdocs account
- Go into the uncertainties package
- Go to "Admin"
- Go to tab for "Maintainers" 
- Add maintainers by user name. I can be added under the username jagerber48. If you add me I would be happy to add the others.

### CODE REVIEW

**Comment by lebigot** [comment]
> @lebigot could you please make me and the other uncertainties maintainers to be maintainers on the uncertainties readthedocs project?

Done! You have been invited to be a maintainer.

**Comment by jagerber48** [comment]
> > @lebigot could you please make me and the other uncertainties maintainers to be maintainers on the uncertainties readthedocs project?
> 
> Thanks for the help. Done! @jagerber48, you have been invited to be a maintainer.

Thank you! That got me what I needed. 

Ok great, I was able to set up readthedocs to detect pull requests and build docs. This is both causing docs to get built for pull requests so we can verify docs build appropriately and look correct. This is also nicely creating a new check in the PR automated checks

image

The built docs can be seen by clicking the link in the action: https://uncertainties--261.org.readthedocs.build/en/261/
The build report can be seen at https://readthedocs.org/projects/uncertainties/builds/25229286/

docs are building for this PR, it is ready for review/approval @newville 

I have some more minor rtd config I'll be doing in the next day or so

**Review by newville — DISMISSED** [review]

**Comment by newville** [comment]
@jagerber48 this seems ok to me.  If we stick with readthedocs as the doc host, I would recommend that all code maintainers were readthedocs admins.

**Comment by jagerber48** [comment]
@newville Sorry, I accidentally dismissed the approval by adding an entry for the changelog. I'll try to remember to do the changelog before requesting review in the future. I also see you accepted the invitation to be a maintainer on readthedocs, great. I  wasn't to send an invite to @andrewgsavage or @wshanks since I couldn't find their accounts on readthedocs.

**Review by newville — APPROVED** [review]
sorry for the delay.... I just noticed that this was still pending approval.

**Pull request merged**
