### PR TITLE
pr_template

### PR DESCRIPTION
**Pull request by andrewgsavage**
I think this is what is needed for github to give a template when opening a PR

### CODE REVIEW

**Review by newville — APPROVED** [review]
Thanks -- that looks great.

**Comment by andrewgsavage** [comment]
we should get pre-commit running first!

**Comment by newville** [comment]
@andrewgsavage oh, right!

**Comment by newville** [comment]
@andrewgsavage Is the file at https://github.com/lmfit/uncertainties/blob/pr221/.pre-commit-config.yaml a reasonable start?  
I forked your PR, added that and pushed it to a "pr221" branch here (I don't know how to push to an open PR from a user branch).   You could take and add that (if it looks acceptable).

**Comment by wshanks** [comment]
Sorry, I haven't had as much time for Uncertainties recently. Ideally the pre-commit check is enforced by the CI, so it might not need to be in the list any way?

You might add some note for the PR author within `<!-- -->` so that it is visible while writing the PR but not in the rendered version to explain how the author should use the list -- put the PR description above/below, check things off or leave them for a reviewer?

**Pull request merged**
